---
title: "Harp seal Growth"
author: "Alejandro Buren"
date: "August 18, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Purpose
This is an analysis of harp seal growth 

* The purpose is to carry out 2 analyses 
    + seasonal growth, accounting for age and sex
    + decadal changes in growth, acconting for seasonality    
    
## Data
* The data was obtained from the Marine Mammals Database  
    + Morph data from qsel_growth in mm_db_queries.accdb
    + Age data from qsel_age in mm_db_queries.accdb 

```{r echo=FALSE, results='hide', warning=FALSE, message=FALSE}
## load libraries ----
library(ggplot2)
library(lubridate)

## read data ----
setwd('D:/Buren_files/GitHub/PG_Growth/')
age <- read.csv('data/PG_age.csv', header = T, as.is = T)
growth <- read.csv('data/PG_growth.csv', header = T, as.is = T)

## merge data sets ----
data <- merge(growth, age[,c('idsex', 'cohortage')], by='idsex', all.x = T)

## wrangle data set ----
# Create dates
data$dayf <- ifelse(is.na(data$day), 1, data$day)
data$dates <- ymd(paste(data$year,"-",data$month,"-",data$dayf,sep = ""))
data$mdates <- ymd(paste('2800',"-",data$month,"-",data$dayf,sep = ""))
for (i in 1:nrow(data)){
  if(!is.na(data[i,'dates'])){
     if(data$month[i] > 7){
       data$mdates[i] <- data$mdates[i] - years(1)
     }
  }
}

# Eliminate foetus, stillborns and starvlings, and YOY
# There is one seal of unknown sex, also eliminate it
# age = 99 does not include any individual in the previous categories
eliminate <- c(0, 91:93)
data <- data[which(!data$cohortage %in% eliminate),]
data <- subset(data, sex != 'U')
rm(eliminate)
subset(data, cohortage == 99)

# create age classes
data$ageclass <- ifelse(data$cohortage > 7, '8+', data$cohortage)


# find outliers in weight by age class
g <- ggplot(data, aes(ageclass, weight))
g + geom_violin() 
print(g)
g

age1 <- subset(data, cohortage == 1)
age1[which(age1$weight > 50),]   

## There is an issue with cohort age! transform to real ages ----

## plots ----
p <- ggplot(data , aes(as.POSIXct(mdates), weight, colour = sex)) 
p <- p + geom_point()
p <- p + scale_x_datetime(date_breaks = "1 months") 
p <- p + theme_bw()
p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1))
p <- p + xlab("Date")
p <- p + facet_wrap(~ageclass, ncol = 1, scales = "free_y")
print(p)



p2 <- ggplot(data , aes(as.POSIXct(dates), weight, colour = sex)) 
p2 <- p2 + geom_point()
p2 <- p2 + scale_x_datetime(date_breaks="1 months") 
p2 <- p2 + theme_bw()
p2 <- p2 + theme(axis.text.x = element_text(angle = 90, hjust = 1))
p2 <- p2 + xlab("Date")
print(p2)

```
